ASPDOTNETCoreBasics/Models/ErrorViewModel.cs
namespace ASPDOTNETCoreBasics.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPDOTNETCoreBasics/Models/LoginViewModel.cs
namespace ASPDOTNETCoreBasics.Models
{
    public class LoginViewModel
    {
        public string Email { get;set; }
        public string Password { get;set; } 
    }
}

ASPDOTNETCoreBasics/Models/UserViewModel.cs
using System.ComponentModel.DataAnnotations;
using ASPDOTNETCoreBasics.Attribute;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASPDOTNETCoreBasics.Models
{
    public class UserViewModel
    {
        [Required(ErrorMessage = "Please Enter Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Enter Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please Enter Password")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please Enter ConfirmPassword")]
        [Compare("Password", ErrorMessage = "Confirm Password doesn't match")]
        public string ConfirmPassword { get; set; }

        [RegularExpression("^[6789]\\d{9}$", ErrorMessage = "Please Enter Correct Contact No.")]
        public string Contact { get; set; }

        [Required(ErrorMessage = "Please Enter Country")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Please Enter City")]
        public string City { get; set; }

        [Required(ErrorMessage = "Please Select Gender")]
        public string Gender { get; set; }
        
        [ValidateCheckBox(ErrorMessage = "Please Accept Terms")]
        public bool Terms { get; set; }
    }
}

ASPDOTNETCoreBasics/Controllers/AccountController.cs
using ASPDOTNETCoreBasics.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPDOTNETCoreBasics.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        
        public IActionResult UserLogin(LoginViewModel model)
        {
            return View("Login");
        }
        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            return View();
        }
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SignUp(UserViewModel model)
        {
            if(ModelState.IsValid)
            {
                return RedirectToAction("Index","Home");
            }
            return View();
        }

    }
}

        //[HttpPost]
        //public IActionResult Login(string Email, string Password)
        //{
        //    return View();
        //}

        //[HttpPost]
        //public IActionResult Login(IFormCollection form)
        //{
        //    string Email = form["email"];
        //    string Password = form["password"];

        //    return View();
        //}
        

ASPDOTNETCoreBasics/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASPDOTNETCoreBasics.Controllers
{
    public class EmployeeController : Controller
    {
        [Route("Employee/Index/{id}/{deptid}")]
        [Route("employee-details/{id}/{deptid}")]
        public IActionResult Index(int id,int deptid)
        {
            return View();
        }
    }
}

ASPDOTNETCoreBasics/Controllers/HomeController.cs
using ASPDOTNETCoreBasics.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASPDOTNETCoreBasics.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPDOTNETCoreBasics/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASPDOTNETCoreBasics.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index(int id,int catid)
        {
            return View();
        }
    }
}

ASPDOTNETCoreBasics/Views/Employee/Index.cshtml
@{
    ViewData["Title"] = "Employee Details";
 
}
<h1>Employee</h1>

ASPDOTNETCoreBasics/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    string name = "Mohan";
}

<div>My Name: @name</div>

@for (var i = 1; i <= 10; i++)
{
    <div>
        @if (i % 2 == 0)
        {
             <div>Even Number: @i</div>
        }
        else
        {
            <div>Odd Number: @i</div>
        }
    </div>
}

ASPDOTNETCoreBasics/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Product Details";
 
}
<h1>Product</h1>

ASPDOTNETCoreBasics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPDOTNETCoreBasics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPDOTNETCoreBasics.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPDOTNETCoreBasics</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="index" asp-route-id="3" asp-route-catId="5">Product</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="index" asp-route-id="3" asp-route-deptId="5">Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASPDOTNETCoreBasics - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>